name: bet_out_app
description: "Bet Out — sports betting companion app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  injectable: ^3.0.0
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.2
  build_runner: ^2.4.8
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
